Issue # 149 bug fixes
Oshlack/splatter pull request #151
Opened 2022-07-21 20:14 UTC by azodichr

- fix Row.names vs rownames bug
- catch and correct batch.size parameter mistake where batch.size is > # samples

2022-08-10 07:48 UTC, lazappi requested changes
Few minor things to take a look at

2022-08-10 07:48 UTC, lazappi commented on R/splatPop-simulate.R
> +    if (quant.norm & ncol(means.pop) > 4){
Should probably use `&&` here

2022-08-10 07:48 UTC, lazappi commented on R/splatPop-simulate.R
> +            set.seed(Sys.time())
What's happening here?

2022-08-10 07:48 UTC, lazappi commented on R/splatPop-simulate.R
> +          warning("Increase nBatches or batch.size...")
Can this be one warning?

2022-09-02 12:41 UTC, lazappi commented
@azodichr Just checking where this is at?

2022-10-10 09:43 UTC, lazappi commented
@azodichr I have made the changes I suggested. Can you please double check I haven't broken anything before I merge this?

2022-10-13 15:02 UTC, azodichr commented
Hi Luke, The changes you made look good on my end. To address your question... the Sys.sleep was an attempt at fixing the problem where when nCells.sample=TRUE it was sampling the nCells for each sample from the gamma distribution, but because the seed is fixed it was sampling the same number each time. 

The sys.sleep was allowing me to set a new seed for each donor using the time stamp. But I figured out a better way would be to adjust the seed for each donor by using the mean expression value for the first gene for that donor - that way it is different for each donor but will be the same each time it is run.

2022-10-14 09:38 UTC, lazappi commented
> To address your question... the Sys.sleep was an attempt at fixing the problem where when nCells.sample=TRUE it was sampling the nCells for each sample from the gamma distribution, but because the seed is fixed it was sampling the same number each time.

Hmmm...I'm not sure I quite understand. Do you mean that each iteration of that for loop was giving the sample number of cells (because something is weird if that is the case)? Or is there something else I'm not following (I've probably forgotten how most of this works)?

In general, I think you are probably setting the seed too many times, for normal Splat I just set it once in the main user function. We actually shouldn't be setting it at all (Bioconductor doesn't approve packages that do that anymore) but that was something I did naively when I first wrote the package and have never got around to implementing a better solution.

2022-10-25 13:01 UTC, lazappi commented
@azodichr I made some changes to remove the extra `set.seed()` calls. I think this solves the issue you had but I might have not quite understood. I also added tests to confirm that:

1. The same number of cells is not being selected for each sample when `nCells.sample = TRUE`
2. The `splatPopSimulate()` seeds are reproducible (i.e. you get identical objects back)

Is there anything else you want to test or does that look ok? The deadline for the next release is next week so I will probably merge this in the next day or two if I don't hear from you.

2022-10-26 20:01 UTC, merged